<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../App/ConvenientNote.DesktopPet.Application/ConvenientNote.DesktopPet.Application.csproj" />
  </ItemGroup>
</Project>

